name: sincroniza
description: "Sincroniza app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  flex_color_scheme: ^8.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  percent_indicator: ^4.2.4
  google_sign_in: ^6.2.2
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.3.0
  sign_button: ^2.0.6
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#1F3339"
  image: assets/images/splash_image.png
  fullscreen: false
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    fullscreen: true
    image: assets/images/splash_image.png
    color: "#1F3339"
    icon_background_color: "#1F3339"
    android_gravity: center
    ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  name: "Sincroniza"
  image_path: "assets/images/ic_bonina.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/images/background_bonina.png"
  adaptive_icon_foreground_inset: 24
  adaptive_icon_foreground: "assets/images/ic_bonina.png"
  web:
    generate: true
    image_path: "assets/images/ic_bonina.png"
    adaptive_icon_background: "assets/images/background_bonina.png"
    adaptive_icon_foreground: "assets/images/ic_bonina.png"