import 'package:sincroniza/models/event.dart';

var eventsList = [
  Event(
    id: 'e1',
    category: "Oficial",
    startDate: DateTime(2025, 2, 6),
    endDate: DateTime(2025, 2, 3),
    eventDay: DateTime(2025, 2, 6),
    startTime: DateTime(2025, 2, 6, 20, 00),
    location: 'Sala Martins Pena',
    title: 'Abertura da Temporada - Os Compositores',
    conductor: 'Cláudio Cohen',
    soloist: 'Anastasiya Evsina',
    eventDetails: [
      'Robert Schumann, Concerto para piano e Orquestra en la menor Op.54 - Solista - Anastasiya Evsina',
      'Sinfonia no.3. em mi bemol maior Op.97 “Renana”',
    ],
  ),
  Event(
    id: 'e2',
    category: "Oficial",
    startDate: DateTime(2025, 2, 10),
    endDate: DateTime(2025, 2, 13),
    eventDay: DateTime(2025, 2, 13),
    startTime: DateTime(2025, 2, 13, 20, 00),
    location: 'Sala Martins Pena',
    title: 'MPB Sinfônico - Ciclo Sinfônico de MPB',
    conductor: 'Fernando Morais',
    soloist: 'Moisés Alves e Ademir Junior',
    eventDetails: [
      'AQUARELA DO BRASIL – FANTASIA PARA ORQUESTRA (ARY BARROSO)',
      'CANÇÕES PRAIEIRAS (DORIVAL CAYMMI)',
      'CARTOLA',
      'MERCEDITA  (RAMON SIXTO RIOS)',
      'LUIZ GONZAGA',
      'EDU LOBO',
      'CHITÃOZINHO E XORORÓ',
      'ELIS',
      'VIESTE   (IVAN LINS)',
      'ESTAÇÃO DA LUZ  (ALCEU VALENÇA)',
      'CHICO BUARQUE - (Trocando em miúdos e Eu te amo)'
    ],
  ),
  Event(
    id: 'e3',
    category: "Oficial",
    startDate: DateTime(2025, 2, 17),
    endDate: DateTime(2025, 2, 20),
    eventDay: DateTime(2025, 2, 20),
    startTime: DateTime(2025, 2, 20, 20, 00),
    location: 'Sala Martins Pena',
    title: 'Concerto Brasileiro',
    conductor: 'Guilherme Bernstein',
    eventDetails: [
      'G.Bernstein: Sinfonia n.3',
      'F. Braga: Episódio Sinfônico',
      'José Guerra Vicente - Abertura  Sinfonica',
      'Leopoldo Miguez: Prometeus, poema sinfônico',
      'Mário Olinto - Valsa Singela',
      'Carlos Gomes - Abertura da Ópera Fosca',
    ],
  ),
  Event(
    id: 'e4',
    category: "Extraordinário",
    startDate: DateTime(2025, 2, 24),
    endDate: DateTime(2025, 2, 24),
    eventDay: DateTime(2025, 2, 24),
    startTime: DateTime(2025, 2, 24, 10, 00),
    location: 'Universidade do DF (Lago Norte)',
    title: 'Concerto Universidade do DF',
  ),
  Event(
    id: 'e5',
    category: "Oficial",
    startDate: DateTime(2025, 2, 24),
    endDate: DateTime(2025, 2, 27),
    eventDay: DateTime(2025, 2, 27),
    startTime: DateTime(2025, 2, 27, 20, 00),
    location: 'Sala Martins Pena',
    title: 'Os Compositore - Tchaikovsky',
    conductor: 'Cláudio Cohen',
    eventDetails: [
      'Abertura Romeu e Julieta',
      'Sinfonia no.6',
    ],
  ),
  Event(
    id: 'e6',
    category: "Extraordinário",
    startDate: DateTime(2025, 3, 6),
    endDate: DateTime(2025, 3, 6),
    eventDay: DateTime(2025, 3, 6),
    startTime: DateTime(2025, 3, 6, 8, 00),
    location: 'Sala Martins Pena',
    title: 'Concerto Didático',
  ),
  Event(
    id: 'e7',
    category: "Oficial",
    startDate: DateTime(2025, 3, 31),
    endDate: DateTime(2025, 4, 3),
    eventDay: DateTime(2025, 4, 3),
    startTime: DateTime(2025, 3, 3, 20, 00),
    location: 'Sala Martins Pena',
    title: 'Concerto ALMUB',
    conductor: 'Cláudio Cohen',
    soloist: 'Fernando Calixto',
    eventDetails: [
      'Jose Guerra Vicente - Carnaval  Carioca',
      'Brahms piano concerto 1',
    ],
  ),
];
